name: characters_api
description: The interface and models for an API providing access to characters.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.17.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.7.0
  json_serializable: ^6.11.0
  test: ^1.21.4
